In [344]:
import numpy as np

In [345]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [346]:
np.ones(2)

array([1., 1.])

In [347]:
np.ones(2)

array([1., 1.])

In [348]:
np.ones((2,3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [349]:
np.zeros((9,9), dtype=np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [350]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [351]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [352]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [353]:
np.eye(2,3, dtype=np.int8, k=1)

array([[0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [354]:
np.eye(4,3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int8)

In [355]:
np.identity(4, dtype=np.int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [356]:
np.identity(4).reshape(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [357]:
np.identity(5).reshape(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [358]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [359]:
np.full((2,3) ,12)

array([[12, 12, 12],
       [12, 12, 12]])

In [360]:
np.full((3,4),123454)

array([[123454, 123454, 123454, 123454],
       [123454, 123454, 123454, 123454],
       [123454, 123454, 123454, 123454]])

In [361]:
np.empty((4,3))

array([[1.01855798e-312, 1.08221785e-312, 1.01855798e-312],
       [9.54898106e-313, 1.01855798e-312, 1.01855798e-312],
       [1.23075756e-312, 1.14587773e-312, 1.06099790e-312],
       [9.76118064e-313, 1.20953760e-312, 1.90979621e-312]])

In [362]:
from random import randint

In [363]:
np.random.randint(12)


9

In [364]:
np.random.randint(12, size=10)

array([ 1, 11,  0,  2,  5, 10,  4,  8,  3,  7])

In [365]:
np.arange(12)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [366]:
 a = np.arange(1,2333)
 a

array([   1,    2,    3, ..., 2330, 2331, 2332])

In [367]:
a[400]

401

In [368]:
np.linspace(1,100, endpoint=True, num = 50, retstep=True)

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

In [369]:
a =np.array([1,2,3,4,5,6,7,8,9])
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [370]:
a.ndim

1

In [371]:
a.dtype

dtype('int32')

In [372]:
a.nbytes

36

In [373]:
a.size

9

In [374]:
a.shape

(9,)

In [375]:
a.itemsize

4

In [376]:
a.sum()

45

In [377]:
a.mean()

5.0

In [378]:
a.std()

2.581988897471611

In [379]:
a.var()

6.666666666666667

In [380]:
a =np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [381]:
a[0]

array([1, 2, 3, 4])

In [382]:
a[1]


array([5, 6, 7, 8])

In [383]:
for item in a:
    print(item)

[1 2 3 4]
[5 6 7 8]


In [384]:
for rows in a:
    for item in rows:
        print(item)

1
2
3
4
5
6
7
8


In [385]:
for item in np.nditer(a):
    print(item)

1
2
3
4
5
6
7
8


In [386]:
a =[1,2,3,4,5,6,7,8,9]
a


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [387]:
for item in enumerate(a):
    print(a)
    

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [388]:
a =["ram","shyam","hari","geeta","sita"]
a

['ram', 'shyam', 'hari', 'geeta', 'sita']

In [389]:
for item in enumerate(a):
    print(item)

(0, 'ram')
(1, 'shyam')
(2, 'hari')
(3, 'geeta')
(4, 'sita')


In [390]:
for k,v in enumerate(a):
    print(k,v)

0 ram
1 shyam
2 hari
3 geeta
4 sita


In [391]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [392]:
for item in np.ndenumerate(a):
    print(item)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


In [393]:
a =[1,2,3]
b =[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [394]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [395]:
a+100


array([101, 102, 103, 104])

In [396]:
a*5

array([ 5, 10, 15, 20])

In [397]:
a=np.array(["Ram","Shyam","Hari","Geeta","Sita","Rakshya","Bibek","kabita","Asbin","sanjeet"])
a

array(['Ram', 'Shyam', 'Hari', 'Geeta', 'Sita', 'Rakshya', 'Bibek',
       'kabita', 'Asbin', 'sanjeet'], dtype='<U7')

In [398]:
a[[True,False,True,False,True,False,True,False,True,True]]


array(['Ram', 'Hari', 'Sita', 'Bibek', 'Asbin', 'sanjeet'], dtype='<U7')

In [399]:
a =np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [400]:
a[[True,False,True,False,True,False,False,True]]

array([1, 3, 5, 8])

In [401]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True])

In [402]:
a[a%2==0]

array([2, 4, 6, 8])

In [403]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
a
              

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [404]:
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [405]:
a[1:,1:3]

array([[10, 11]])

In [406]:
a=np.arange(1,50).reshape(7,7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [407]:
a[4:6:2,3:5]

array([[32, 33]])

In [408]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [409]:
b =a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [410]:
b[7]=100
b

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9])

In [411]:
a

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9])

In [412]:
a=np.arange(1,51)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [413]:
b =a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [414]:
b[12]=123456
b

array([     1,      2,      3,      4,      5,      6,      7,      8,
            9,     10,     11,     12, 123456,     14,     15,     16,
           17,     18,     19,     20,     21,     22,     23,     24,
           25,     26,     27,     28,     29,     30,     31,     32,
           33,     34,     35,     36,     37,     38,     39,     40,
           41,     42,     43,     44,     45,     46,     47,     48,
           49,     50])

In [415]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [416]:
a =np.arange(1,50)

In [417]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [418]:
np.reshape(a,(7,7))

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [419]:
np.reshape(a,(7,7))

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [420]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [421]:
b = np.resize(a, (3,4))
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1]])

In [422]:
a.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [423]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [424]:
c = a.flatten()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [425]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [426]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [427]:
a =np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [428]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [429]:
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [430]:
np.concatenate((a,b), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [431]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [432]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [433]:
np.stack((a,b), axis=1)

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 3,  4,  5],
        [13, 14, 15]],

       [[ 6,  7,  8],
        [16, 17, 18]]])

In [434]:
np.stack((a,b), axis=0)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [435]:
a = np.arange(1,50).reshape(7,7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [436]:
b= np.arange(50,99).reshape(7,7)
b

array([[50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90, 91],
       [92, 93, 94, 95, 96, 97, 98]])

In [437]:
np.stack((a,b), axis=1)

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [50, 51, 52, 53, 54, 55, 56]],

       [[ 8,  9, 10, 11, 12, 13, 14],
        [57, 58, 59, 60, 61, 62, 63]],

       [[15, 16, 17, 18, 19, 20, 21],
        [64, 65, 66, 67, 68, 69, 70]],

       [[22, 23, 24, 25, 26, 27, 28],
        [71, 72, 73, 74, 75, 76, 77]],

       [[29, 30, 31, 32, 33, 34, 35],
        [78, 79, 80, 81, 82, 83, 84]],

       [[36, 37, 38, 39, 40, 41, 42],
        [85, 86, 87, 88, 89, 90, 91]],

       [[43, 44, 45, 46, 47, 48, 49],
        [92, 93, 94, 95, 96, 97, 98]]])

In [438]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [439]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [440]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [441]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [442]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [443]:
np.zeros((7,8), dtype=np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [444]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [445]:
np.ones((3,4), dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [446]:
np.ones((5,7,6), dtype=np.int8)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int8

In [447]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [448]:
np.full((4,5), 45)

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [449]:
np.full((3,4),34)

array([[34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34]])

In [450]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [451]:
np.eye(3,4, dtype=np.int8,k=1 )

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [452]:
np.eye(4,4 , dtype=np.int8, k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int8)

In [453]:
np.identity(7, dtype=np.int8)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [454]:
np.identity(1, dtype=np.int8)

array([[1]], dtype=int8)

In [455]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [457]:
np.arange(20, dtype=np.int8)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int8)

In [458]:
np.linspace(1,100, endpoint=True, num =50, retstep=True)

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

In [459]:
from numpy.random import randint

In [461]:
np.random.randint(8,size=10)

array([1, 5, 3, 2, 1, 3, 1, 5, 4, 3])

In [462]:
np.empty(20)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
       7.56587585e-307, 1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
       1.78020169e-306, 7.56601165e-307, 1.02359984e-306, 2.78149851e-307,
       1.06811422e-306, 8.45590539e-307, 6.23054972e-307, 9.34609790e-307,
       1.78019354e-306, 1.69119330e-306, 1.24611470e-306, 2.56765117e-312])

In [463]:
a =np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [464]:
for rows in a:
    for item in rows:
        print(item)

1
2
3
4
5
6
7
8
9
10


In [465]:
for item in np.nditer(a):
    print(item)

1
2
3
4
5
6
7
8
9
10


In [466]:
a =["umesh","Bibek","Ram","Shyam"]
a

['umesh', 'Bibek', 'Ram', 'Shyam']

In [467]:
for item in enumerate(a):
    print(item)

(0, 'umesh')
(1, 'Bibek')
(2, 'Ram')
(3, 'Shyam')


In [468]:
for k,v in enumerate(a):
    print(k,v)

0 umesh
1 Bibek
2 Ram
3 Shyam


In [469]:
for b,c in enumerate(a):
    print(b,c)

0 umesh
1 Bibek
2 Ram
3 Shyam


In [470]:
a =np.array([[1,2,3,4],[5,6,7,8]])

In [471]:
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [472]:
for item in np.ndenumerate(a):
    print(item)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


In [473]:
a =[1,2,3,4,5]
b=[6,7,8,9]
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [474]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
a+b

array([ 7,  9, 11, 13, 15])

In [479]:
a =np.array(["Ram","shyam","Hari","Geeta","Sita"])
a

array(['Ram', 'shyam', 'Hari', 'Geeta', 'Sita'], dtype='<U5')

In [483]:
a[[True,False,True,False,False]]

array([], shape=(0, 5), dtype='<U5')

In [484]:
a =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [485]:
a[a%2==0]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [486]:
a[[a%2==0]]

C:\Users\admin\AppData\Local\Temp\ipykernel_1044\538444601.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[[a%2==0]]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [487]:
a=np.arange(1,50).reshape(7,7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [489]:
a[4:6,5:6]

array([[34],
       [41]])

In [491]:
a[0:,0:7:2]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14],
       [15, 17, 19, 21],
       [22, 24, 26, 28],
       [29, 31, 33, 35],
       [36, 38, 40, 42],
       [43, 45, 47, 49]])

In [493]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [494]:
a.ndim

2

In [496]:
a.dtype

dtype('int32')

In [497]:
a.nbytes


40

In [498]:
a.itemsize

4

In [499]:
a.mean()

5.5

In [500]:
a.sum()

55

In [501]:
a.std()

2.8722813232690143

In [502]:
a.var()

8.25

In [503]:
a =np.array([1,2,3,4,5,67,8])
a

array([ 1,  2,  3,  4,  5, 67,  8])

In [504]:
b=a
b

array([ 1,  2,  3,  4,  5, 67,  8])

In [505]:
b[2]=90
b

array([ 1,  2, 90,  4,  5, 67,  8])

In [506]:
a

array([ 1,  2, 90,  4,  5, 67,  8])

In [507]:
a=np.arange(20)

In [508]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [509]:
b=a.copy()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [510]:
b[9]=987654
b

array([     0,      1,      2,      3,      4,      5,      6,      7,
            8, 987654,     10,     11,     12,     13,     14,     15,
           16,     17,     18,     19])

In [511]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [513]:
a=np.arange(1,57).reshape(7,8)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56]])

In [517]:
b=a.reshape(14,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56]])

In [518]:
a =np.arange(1,64)

In [519]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [525]:
np.resize(a, (23,4))



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [526]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [530]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])


In [531]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [532]:
np.stack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [534]:
a=np.arange(1,50).reshape(7,7)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [535]:
b= np.arange(50,99).reshape(7,7)
b

array([[50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90, 91],
       [92, 93, 94, 95, 96, 97, 98]])

In [538]:
np.stack((a,b), axis=1)

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [50, 51, 52, 53, 54, 55, 56]],

       [[ 8,  9, 10, 11, 12, 13, 14],
        [57, 58, 59, 60, 61, 62, 63]],

       [[15, 16, 17, 18, 19, 20, 21],
        [64, 65, 66, 67, 68, 69, 70]],

       [[22, 23, 24, 25, 26, 27, 28],
        [71, 72, 73, 74, 75, 76, 77]],

       [[29, 30, 31, 32, 33, 34, 35],
        [78, 79, 80, 81, 82, 83, 84]],

       [[36, 37, 38, 39, 40, 41, 42],
        [85, 86, 87, 88, 89, 90, 91]],

       [[43, 44, 45, 46, 47, 48, 49],
        [92, 93, 94, 95, 96, 97, 98]]])

In [539]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7, 50, 51, 52, 53, 54, 55, 56],
       [ 8,  9, 10, 11, 12, 13, 14, 57, 58, 59, 60, 61, 62, 63],
       [15, 16, 17, 18, 19, 20, 21, 64, 65, 66, 67, 68, 69, 70],
       [22, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 77],
       [29, 30, 31, 32, 33, 34, 35, 78, 79, 80, 81, 82, 83, 84],
       [36, 37, 38, 39, 40, 41, 42, 85, 86, 87, 88, 89, 90, 91],
       [43, 44, 45, 46, 47, 48, 49, 92, 93, 94, 95, 96, 97, 98]])